<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDDc8vEc\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDDc8vEc/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerDDc8vEc.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerDDc8vEc\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerDDc8vEc\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'DDc8vEc',
    'container.build_id' => '439a05f9',
    'container.build_time' => 1553453842,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDDc8vEc');
