<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQZ2skA5\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQZ2skA5/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQZ2skA5.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQZ2skA5\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerQZ2skA5\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'QZ2skA5',
    'container.build_id' => '22fb0e48',
    'container.build_time' => 1550579669,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQZ2skA5');
